"""make short code nullable

Revision ID: 209416deead3
Revises: 5f5d7cc0621d
Create Date: 2026-08-02 12:13:58.389014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '209416deead3'
down_revision: Union[str, Sequence[str], None] = '5f5d7cc0621d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('urls', 'short_code',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.drop_index(op.f('ix_urls_alias'), table_name='urls')
    op.create_index(op.f('ix_urls_title'), 'urls', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_urls_title'), table_name='urls')
    op.create_index(op.f('ix_urls_alias'), 'urls', ['title'], unique=False)
    op.alter_column('urls', 'short_code',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    # ### end Alembic commands ###
