"""add alias to URL model

Revision ID: 3c416c0d06a8
Revises: 8729210a23de
Create Date: 2026-08-01 13:30:23.292197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c416c0d06a8'
down_revision: Union[str, Sequence[str], None] = '8729210a23de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('urls', sa.Column('alias', sa.String(length=100), nullable=False))
    op.create_index(op.f('ix_urls_alias'), 'urls', ['alias'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_urls_alias'), table_name='urls')
    op.drop_column('urls', 'alias')
    # ### end Alembic commands ###
