"""implement click model

Revision ID: 41d36d5c8984
Revises: 108b21de37a8
Create Date: 2026-08-03 23:06:19.413409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41d36d5c8984'
down_revision: Union[str, Sequence[str], None] = '108b21de37a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clicks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url_id', sa.Integer(), nullable=False),
    sa.Column('clicked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('referer', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['url_id'], ['urls.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clicks_id'), 'clicks', ['id'], unique=False)
    op.create_index(op.f('ix_clicks_url_id'), 'clicks', ['url_id'], unique=False)
    op.alter_column('urls', 'expires_in_days',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('urls', 'expires_in_days',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_clicks_url_id'), table_name='clicks')
    op.drop_index(op.f('ix_clicks_id'), table_name='clicks')
    op.drop_table('clicks')
    # ### end Alembic commands ###
