"""rename 'alias' to 'title'

Revision ID: 5f5d7cc0621d
Revises: a78985dedf24
Create Date: 2026-08-01 13:51:16.249644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f5d7cc0621d'
down_revision: Union[str, Sequence[str], None] = 'a78985dedf24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'urls', 
        'alias', 
        new_column_name='title'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
            'urls', 
            'alias', 
            new_column_name='title'
        )
    # ### end Alembic commands ###
