"""make expires_at integer instead of datetime

Revision ID: 8127e1334f77
Revises: 209416deead3
Create Date: 2026-08-02 12:57:18.308034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8127e1334f77'
down_revision: Union[str, Sequence[str], None] = '209416deead3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('urls', sa.Column('expires_in_days', sa.Integer(), nullable=True))
    op.drop_column('urls', 'expires_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('urls', sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_column('urls', 'expires_in_days')
    # ### end Alembic commands ###
